# Database Connection
# Critical for MySQL to combine inserts into one string
spring.datasource.url=jdbc:mysql://localhost:3306/option_chain_db?rewriteBatchedStatements=true
spring.datasource.username=oc_admin
spring.datasource.password=Aq!sw2de3

# Hibernate Strategy: Create if not exists, otherwise update
spring.jpa.hibernate.ddl-auto=update

# Show SQL for debugging (optional)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Enable Hibernate Batching
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# 4. Optional: View batching in action (Check "Batcher" logs)
logging.level.org.hibernate.engine.jdbc.batch.internal.BatchingBatch=TRACE

# Define the log file name and location
logging.file.name=logs/oc-analyzer.log

# Roll the log file every day and keep logs for 30 days
logging.logback.rollingpolicy.file-name-pattern=logs/oc-analyzer-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-history=0
logging.logback.rollingpolicy.clean-history-on-start=false


# Custom Log Format to match your requirement
# Updated pattern: Time(ms) | Level | Thread | Message
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%thread] %logger{36}.%M:%L - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%thread] %logger{36}.%M:%L - %msg%n


# Dhan API Configuration
dhan.api.host=https://api.dhan.co
dhan.api.endpoint=/v2/optionchain
dhan.api.client-id=1107674922
dhan.api.access-token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJkaGFuIiwicGFydG5lcklkIjoiIiwiZXhwIjoxNzc0NzY1OTQzLCJpYXQiOjE3NzQ2Nzk1NDMsInRva2VuQ29uc3VtZXJUeXBlIjoiU0VMRiIsIndlYmhvb2tVcmwiOiIiLCJkaGFuQ2xpZW50SWQiOiIxMTA3Njc0OTIyIn0.tXXR8QVOaibphMS4GgXv5R8CCWbHnz9PeaV-Mkjy2_rfz7CQm9tTyT6EdhAWKXAhk8BgjGH4Mc2TSzkn-UjVvQ
dhan.api.oc.payload.underlyingScrip=26000
dhan.api.oc.payload.underlyingSeg=NSE_FNO